const colors = require("tailwindcss/colors");

module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "media",
  plugins: [require("@tailwindcss/forms")],
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      primary: "#6744AC",
      primaryDark: "#4D337F",
      secondary: "#f1D3D5",
      third: "#EDEDF8",
      darkgray: "#212121",
      lightgray: "#F6F6F9",
      black: colors.black,
      white: colors.white,
      gray: colors.gray,
      red: colors.red,
      yellow: colors.amber,
      green: colors.emerald,
      blue: colors.blue,
      indigo: colors.indigo,
      purple: colors.violet,
      pink: colors.pink,
    },
    spacing: {
      px: "1px",
      0: "0px",
      0.5: "0.125rem",
      1: "0.25rem",
      1.5: "0.375rem",
      2: "0.5rem",
      2.5: "0.625rem",
      3: "0.75rem",
      3.5: "0.875rem",
      4: "1rem",
      5: "1.25rem",
      6: "1.5rem",
      7: "1.75rem",
      8: "2rem",
      9: "2.25rem",
      10: "2.5rem",
      11: "2.75rem",
      12: "3rem",
      14: "3.5rem",
      16: "4rem",
      20: "5rem",
      24: "6rem",
      28: "7rem",
      32: "8rem",
      36: "9rem",
      40: "10rem",
      44: "11rem",
      48: "12rem",
      52: "13rem",
      56: "14rem",
      60: "15rem",
      64: "16rem",
      72: "18rem",
      80: "20rem",
      96: "24rem",
    },
    fontFamily: {
      axiformaHeavy: ["axiforma-heavy"],
      axiformaMedium: ["axiforma-medium"]
    },
    fontSize: {
      xs: ["0.688rem", { lineHeight: "1rem" }],
      sm: ["0.75rem", { lineHeight: "1rem" }],
      base: ["0.9rem", { lineHeight: "1rem" }],
      lg: ["0.875rem", { lineHeight: "1rem" }],
      xl: ["0.938rem", { lineHeight: "1rem" }],
      "2xl": ["1.1rem", { lineHeight: "1.5rem" }],
      "3xl": ["1.4rem", { lineHeight: "2rem" }],
      "4xl": ["2rem", { lineHeight: "2.5rem" }],
      "5xl": ["2.5rem", { lineHeight: "2.75rem" }],
      "6xl": ["3rem", { lineHeight: "2.75rem" }],
      "7xl": ["3.5rem", { lineHeight: "2.75rem" }],
      "8xl": ["4rem", { lineHeight: "2.75rem" }],
      "9xl": ["4.5rem", { lineHeight: "2.75rem" }],
    },
  },
};
